version: '3'
services:
  app:
    container_name: cloud_comp
    restart: always
    build: .
    ports:
      - '8080:8080'
      - '8081:8081'
    links:
      - mongo
  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - '27017:27017'
