CREATE DATABASE IF NOT EXISTS test;
USE test;
CREATE TABLE IF NOT EXISTS sample_data (
    id INT NOT NULL AUTO_INCREMENT,
    age INT NOT NULL,
    weight_kg_current DECIMAL(10 , 2 ) NOT NULL,
    weight_kg_2019 DECIMAL(10 , 2 ) NOT NULL,
	weight_kg_2018 DECIMAL(10 , 2 ) NOT NULL,
	height INT NOT NULL,
	sex INT NOT NULL,
    PRIMARY KEY (id)
);
LOAD DATA LOCAL INFILE './sample_data_mysql.csv' 
INTO TABLE sample_data
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS;